version: "3"

  services: 
  mssql-usdafooddb: 
    image: microsoft/mssql-server-linux:latest
    container_name: mssql-usdafooddb 
    ports: 
      - 1433:1433 
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=password123! 
      - COMPOSE_HTTP_TIMEOUT=120
